name: Run Node CJS Script

on:
  push:
    branches:
      - main  # bisa diubah sesuai branch yang kamu mau
  workflow_dispatch:  # ini buat manual trigger

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Node CJS file
        run: node ema_crossover_rsi_macd_filtered.js FARTCOIN1_8-25.json 0.01
